require: rubocop-rails

AllCops:
  Exclude:
    - 'bin/**/*'
    - 'config/**/*'
    - 'db/**/*'
    - 'spec/rails_helper.rb'
    - 'spec/spec_helper.rb'
    - 'vendor/**/*'
    - 'Gemfile'
    - 'Rakefile'

Rails/ApplicationController:
  Enabled: false

Rails/Output:
  Enabled: false

Rails/HasManyOrHasOneDependent:
  Enabled: false

Rails/InverseOf:
  Enabled: false

Metrics/AbcSize:
  Exclude:
    - 'app/services/**/*'

Metrics/MethodLength:
  Exclude:
    - 'app/helpers/**/*'
    - 'app/services/**/*'
    - 'app/controllers/concerns/exception_handling.rb'

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - 'app/controllers/concerns/exception_handling.rb'

Style/FrozenStringLiteralComment:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/StructInheritance:
  Enabled: false

Style/RedundantBegin:
  Enabled: false

Style/RescueStandardError:
  Enabled: false

Style/RescueModifier:
  Enabled: false

Naming/MethodParameterName:
  Enabled: false
