version: '3.7'

services:
  gym:
    build: .
    image: gym
    container_name: gym
    restart: on-failure
    depends_on:
      - postgres
      - redis
    volumes:
      - .:/app:delegated
      - bundle_volume:/usr/local/bundle
    ports:
      - 3000:3000
    env_file:
      - .env

  postgres:
    image: postgres:13.1-alpine
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    env_file:
      - .env

  redis:
    image: redis:5-alpine
    restart: always
    volumes:
      - redis_data:/data
    ports:
      - 6379:6379

volumes:
  postgres_data:
  redis_data:
  bundle_volume:
