name: build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Pull Docker images
      run: docker-compose pull
    - name: Run postgresql
      run: docker-compose up -d postgres
    - name: Build the Docker image
      run: docker-compose build
    - name: Prepare DB
      run: docker-compose run gym bundle exec rails db:create db:schema:load RAILS_ENV=test
    - name: Run tests
      run: docker-compose run gym bundle exec rspec
